### ISSUE TITLE
Where is the rest of the pre-generated data?

### ISSUE THREAD

**Issue by mathemakitten** [google-deepmind/mathematics_dataset#10]
hi! I'm looking to reproduce the results in the paper but when downloading from [this link on the README](https://console.cloud.google.com/storage/browser/mathematics-dataset/), the .tar file only contains `train-medium`. 

The github README says `Note the training data for each question type is split into "train-easy", "train-medium", and "train-hard".`

Should the train-easy, train-hard, and test-easy/medium/hard datasets be included in the pre-generated files off of GCP, or do we need to generate it ourselves? If the latter, how can we ensure that the generated data/results are the exact same as the paper?

**Comment by davidsaxton** [comment]
I've just downloaded the .tar.gz file and confirmed it contains the subdirectories interpolate, extrapolate, train-easy, train-medium, train-hard (and the file train-readme.txt).

Please re-download and extract again, possibly you had an incomplete download? If your issue persists please reopen this issue.
