### ISSUE TITLE
Problem generating examples

### ISSUE THREAD

**Issue by yvargasp1** [google-deepmind/mathematics_dataset#12]
![issue](https://user-images.githubusercontent.com/60678085/82509974-fdc97400-9ace-11ea-86d9-3e8d7b47a358.JPG)

Can you help me , with this problem ? .

**Comment by yvargasp1** [comment]
I run the command at the anaconda prompt: "python -m mathematics_dataset.generate --filter = linear_1d" and "python -m mathematics_dataset.generate_to_file --output_drir = '..', and the second just create the empty file without any data" .

**Comment by akpandeya** [comment]
np.int32 is not recognized as integer. Please change the two files and it would do the job.
1. mathematics_dataset\mathematics_dataset\sample\number.py
Line number 144 becomes :
  return isinstance(value, (int, np.int64, np.int32, sympy.Integer))
Like this:
![change 1](https://user-images.githubusercontent.com/10657123/85315116-c0d01300-b4ba-11ea-82da-68f94e5901b4.png)

2. mathematics_dataset\mathematics_dataset\sample\ops.py
Add another line below line 205 such that line 202-207 become:

    elif (isinstance(self._value, int)
          or isinstance(self._value, sympy.Integer)
          or isinstance(self._value, display.Decimal)
          or isinstance(self._value, np.int64)
          or isinstance(self._value, np.int32)):
      return self._value >= 0
Like this:
![change 2](https://user-images.githubusercontent.com/10657123/85315114-c0377c80-b4ba-11ea-9b51-abc6087225cd.png)

**Comment by akpandeya** [comment]
Or you could clone my forked version:
https://github.com/akpandeya/mathematics_dataset

**Comment by davidsaxton** [comment]
Thanks Avanindra for the PR!
