### ISSUE TITLE
public dataset filename is ambiguous

### ISSUE THREAD

**Issue by justindujardin** [google-deepmind/mathematics_dataset#2]
Thanks for sharing this excellent work. 

When downloading the [generated dataset](https://storage.cloud.google.com/mathematics-dataset/v1.0.tar.gz), the filename is `v1.0.tar.gz`. 

Consider changing it to something like `mathematics-dataset-v1.0.tar.gz` so it doesn't appear ambiguous in download folders?

**Comment by davidsaxton** [comment]
Good suggestion - name updated.
