### ISSUE TITLE
Train and evaluate problem

### ISSUE THREAD

**Issue by YongtaoGE** [google-deepmind/mathematics_dataset#4]
Hi, there! It is really a nice work. I have a question when using the dataset. Does it refer to train a single neural network model for all kind of mathematics questions or train many neural network models individually for different type of modules in the paper?

**Comment by davidsaxton** [comment]
In the paper we train a single neural network (motivation - want general mathematical abilities, not lots of individual ones). But obviously you're free to use the dataset how you like!
