### ISSUE TITLE
Generate mathematical statements rather than questions

### ISSUE THREAD

**Issue by TianrenWang** [google-deepmind/mathematics_dataset#8]
Is there an easy way to modify the code in this repo so that you can generate statements rather than questions?

For example, instead of generating a sample with Question "What is 4 + 4?" and Answer "8". Is it possible to generate the statement "4 + 4 = 8"?

**Comment by davidsaxton** [comment]
The code is pretty easy to modify assuming you know python. E.g., to change the addition question, you could modify some of the templates here: https://github.com/deepmind/mathematics_dataset/blob/master/mathematics_dataset/modules/arithmetic.py#L141 (maybe putting what you want just as a question template), then modify the generation to only print out the question (see e.g., https://github.com/deepmind/mathematics_dataset/blob/master/mathematics_dataset/generate.py)
