### ISSUE TITLE
Question about baseline results

### ISSUE THREAD

**Issue by reiinakano** [google-deepmind/mathematics_dataset#9]
Did you use beam search for the accuracy values reported in the paper? If so, is the accuracy top1 accuracy or top K accuracy?

**Comment by davidsaxton** [comment]
No beam search; the models output the most probably character sequentially for every output character.

"As is common in sequence-to-sequence models, the models predict the answer autoregressively using a greedy decoder (output majority class at each step)." (section 4.1)

**Comment by reiinakano** [comment]
Ah thanks, I missed that
